### ISSUE TITLE
UX/UI enhancement: Blank syndication links being syndicated

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/syndication-links#23] opened 2016-05-18 18:19 UTC
![woodwind](https://cloud.githubusercontent.com/assets/5882943/15369012/8beee060-1ce5-11e6-90f1-df8f8d6a4ec5.PNG)

I've seen blank versions of syndicated links appear on various platforms, the one above is a capture from the reader Woodwind.xyz. I've also noticed it when syndicating to tumblr.com and Facebook (though I've removed it programatically since). I'm not sure if I've seen them display on other sources (in most cases I choose to use the icon versions rather than text, but could do a quick test to see if the text at least appears.)  Since I'm sure there are others, I'm curious if there's a way to either fix how these show up (or not) or simply move them for POSSEd copies?  

Thoughts on UX/UI:
I'm presuming that they're hooked onto the end of the_content(), which then means that they're being syndicated out as part of the body of the content.  I would suggest that on most platforms, most people don't/won't care about the fact that there are syndicated copies (though for the near term of advertising the concept for the IndieWeb, keeping them may be valuable), particularly when they can view the primary source which ought to presumably have all the commentary and webmentions (by backfeed or other means).

Interestingly, I occasionally see, though not as often, the "Share This" data flow through in the same manner. In my case the share this appears _above_ the list of syndicated links: viz: 
![share this](https://cloud.githubusercontent.com/assets/5882943/15369752/deb86c00-1ce8-11e6-9182-f0014f3a2938.PNG)
Is there some type of processing that Jetpack is doing to prevent this from syndicating as "content"?

The way I typically think about it, knowing about syndicated copies is mostly useful as a function of commenting rather than content, so that if someone comments in Facebook, for example, I go back to that silo to post a response, so their chosen platform can send notifications/emails etc about the interaction, and rely on webmentions to backport my own comment onto my site and to keep the flow of conversation on the original post rather than a separate post on my own site that points back to another.  Perhaps then, the best default location for syndication links is within the comments section? This then solves the problem of syndicating out blank versions, but more closely associates the syndicated copies with the "conversation" about the post. Potentially putting them at the top of the comments section could also keep them relatively close to where they currently live as a default.

I pose most of this as ideas/potential suggestions, but I'm curious what others think in terms of what/how they use this functionality.

**Comment by dshanske** [comment] 2016-05-18 18:48
I haven't been able to reproduce this. But I am working on refactoring the code. The blank on other platforms is likely due to using an icon font as opposed to SVG(which I switched to in Post Kinds).

**Comment by dshanske** [comment] 2016-05-28 16:21
Fixed in SVG icon version. Will deploy to Wordpress.org when stable.

**Closed by dshanske** 2016-05-28 16:21 UTC
