### ISSUE TITLE
'Empty' Syndicate links area appears on content listings when disabled in settings

### ISSUE THREAD

**Issue by ndegruchy** [dshanske/syndication-links#148] opened 2022-01-08 00:23 UTC
Hello,

I seem to have stumbled across a bug. While using the TwentyTwentyOne theme, and having "Show on Front Page, Archive Pages, and Search Results" disabled, I still get an 'empty' syndicate link section for any post that has one. This displays fine on single pages, but it shouldn't be (per the preference) be showing on content listing pages.

The HTML section looks like this:

```html
<div class="syndication-links">
  <ul class="relsyn">
    <li>
      <a aria-label="fosstodon.org" class="u-syndication syn-link" href="https://fosstodon.org/@nathand/107581317212003683"> </a>
    </li>
  </ul>
</div>
```
As you can see, the list item has no content, but it still takes up space. I can account for this in my theme, but it seems like there might be a missing check for `is_front` or similar.

Here's a snippet of my configuration. You can see the issue on my [homepage][1]. Or these screenshots:

![0B4DuHXB9q](https://user-images.githubusercontent.com/52262673/148623340-3425d83a-1427-49c9-a3ee-ef09c4946d60.png)
![IN9JNPoAP8](https://user-images.githubusercontent.com/52262673/148623342-551b8685-0292-4109-a90b-ed8186ad3591.png)

```
### wp-core ###

version: 5.8.3

### wp-parent-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.4
author: the WordPress team
author_website: https://wordpress.org/
auto_update: Enabled

Semantic-Linkbacks: version: 3.11.0, author: Matthias Pfefferle, Auto-updates enabled
```
[1]: https://degruchy.org/

**Comment by dshanske** [comment] 2022-01-09 03:37
They are meant to be hidden, not removed. There is still an advantage to having them in the page. The issue is that they are still taking up visual space. Will fix that.

**Comment by dshanske** [comment] 2022-01-09 04:16
Should be fixed in the latest release.

**Closed as completed by dshanske** 2022-01-09 04:16 UTC
