### ISSUE TITLE
Add support for Keyring Social Importers

### ISSUE THREAD

**Issue by xavierroy** [dshanske/syndication-links#73] opened 2018-01-18 03:35 UTC
Posts imported through Keyring Social Importers plugin require setting up  the syndicated links manually. The plugin stores the original link data in custom fields. So I'm guessing it might be possible to pull it out and add it to the SynLinks meta box.

**Comment by dshanske** [comment] 2018-02-25 05:42
Dupe of #65

**Closed by dshanske** 2018-02-25 05:42 UTC
